spring.application.name=custodia-360

# Habilitar la consola
spring.h2.console.enabled=true

# Ruta para acceder (puedes cambiarla si quieres, ej: /debug-db)
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:custodia360_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver

app.upload.dir=./uploads

# Tamaño máximo por cada archivo individual
spring.servlet.multipart.max-file-size=6MB

# Tamaño máximo total de la solicitud (por si envías varios archivos)
spring.servlet.multipart.max-request-size=6MB